---
title: "Project 3: STAT302package Tutorial"
author: Eunice Zhang
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{STAT302package Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<!--- Begin styling code. --->
<style type="text/css">
/* Whole document: */
body{
  font-family: "Palatino Linotype", "Book Antiqua", Palatino, serif;
  font-size: 12pt;
}
h1.title {
  font-size: 38px;
  text-align: center;
}
h4.author {
  font-size: 18px;
  text-align: center;
}
h4.date {
  font-size: 18px;
  text-align: center;
}
</style>
<!--- End styling code. --->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r setup, include=FALSE}
library(STAT302package)
```

### Introduction Paragraph

## T-test
```{r}
# Function: my_t.test, performs a one sample t-test
# Input: 
# x, a numeric vector of data; 
# alternative, a character string specifying the alternative hypothesis;
# mu, a number indicating the null hypothesis value of the mean
# Output: a list with four elements, test_stat, df, alternative, and p_value

my_t.test <- function(x, alternative, mu) {
  # calculate the different values
  estimate <- mean(x)
  df <- length(x) - 1
  se <- sd(x) / sqrt(length(x))
  t_obs <- (estimate - mu) / se
  
  # return the output based on different alternative hypothesis
  if (alternative == "less") {
    p_value <- pt(t_obs, df, lower.tail = TRUE)
  } else if (alternative == "greater") {
    p_value <- pt(t_obs, df, lower.tail = FALSE)
  } else {
    p_value <- 2 * pt(abs(t_obs), df, lower.tail = FALSE)
  }
  
  result <- list("test_stat" = t_obs,
                 "df" = df,
                 "alternative" = alternative,
                 "p_val" = p_value)
  return(result)
}

# Demonstrate a test of the hypothesis (Two-Sided)

set.seed(123)
x <- rbinom(100, size = 7, prob = 0.1)

# result returned by my_t.test()
my_t.test(x, "less", 0.9)

# result returned by t.test()
t.test(x, mu = 0.9, alternative = "less")
```

